name: Stress Test

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  stress-test:
    name: Stress Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install stress tool
        run: sudo apt-get update && sudo apt-get install stress -y

      - name: Stress CPU
        run: stress --cpu 8 --timeout 180s  # Stress CPU for 2 minutes using 8 workers

      - name: Stress Memory
        run: stress --vm 8 --vm-bytes 2G --timeout 120s  # Stress memory for 2 minutes using 8 workers and 1GB each

      - name: Stress Disk
        run: |
          dd if=/dev/zero of=/tmp/test bs=1M count=1024 conv=fdatasync  # Write 1GB of zeros to /tmp/test
          rm /tmp/test  # Delete the temporary file after writing

