name: "CodeQL"

on:
  push:
    branches: [ main, codeQL ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, codeQL ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ] # Add other languages as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    # If you wish to specify custom build commands, remove the autobuild step
    # and uncomment the following three lines.
    # - run: |
    #     ./configure
    #     make

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{ matrix.language }}"
