name: Stress Test and Autoscale Runners

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours (adjust as needed)

jobs:
  stress-test:
    name: Stress Test Runners
    runs-on: self-hosted
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Replace with your dependency installation command

      - name: Run stress test
        run: |
          npm run stress-test  # Replace with your stress testing command

  autoscale:
    name: Autoscale Runners
    runs-on: self-hosted
    needs: stress-test
    steps:
      - name: Setup Kubernetes CLI
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Scale Runners
        run: |
          # Your scaling script goes here
          # Example:
          # kubectl scale --replicas=3 deployment/actions-runner-controller -n actions-runner-system
